language: node_js

node_js:
  - "8"

cache:
  directories:
    "node_modules"

before_install:
  - npm install
  - printf "//registry.npmjs.org/:_authToken=${NPM_TOKEN}" >> ~/.npmrc

before_script:
  - npm run build

after_success:
  - npm run test

on:
  branch: master

deploy:
  provider: npm
  email: "contato@brunomacedo.com.br"
  api_key: $NPM_API_KEY
