language: node_js

node_js:
  - "8"

cache:
  yarn: true
  directories:
    - node_modules

before_install:
  - yarn

before_script:
  - yarn build

after_success:
  - yarn test

on:
  branch: master

deploy:
  provider: npm
  email: "contato@brunomacedo.com.br"
  api_key: $NPM_API_KEY
